# Server Configuration
server:
  port: 8081

  # Database Configuration
  error:
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gamehive
    username: root
    password:

  liquibase:
    change-log: db/master.xml
    enabled: false



application:
  service:
    impl: test
